
{
  "settings": {
    "$type": "Settings, DionicGame",
    "graphicsQuality": 2,
    "resolutionX": 1600,
    "resolutionY": 900,
    "displayMode": 1,
    "uiScale": 1.0,
    "totalVolume": 0.5,
    "soundEffectsVolume": 1.0,
    "musicVolume": 1.0,
    "language": "polish",
    "cameraSpeed": 1.0,
    "cameraPanning": 0,
    "edgeScrolling": 1,
    "confinedCursor": 0,
    "devMode": 0,
    "runningInBackground": 0,
    "showTutorials": 1,
    "vsync": 0,
    "graphicsSettings": {
      "antiAliasing": true,
      "shadows": 3,
      "textureResolution": 2,
      "overallQuality": 2,
      "particles": true,
      "animations": true,
      "grass": true,
      "lod": 2,
      "terrainLOD": 3
    },
    "keybindings": {
      "CameraMoveForward": "W",
      "CameraMoveBack": "S",
      "CameraMoveLeft": "A",
      "CameraMoveRight": "D",
      "CameraPanning": "Mouse1",
      "CameraRotate": "Mouse2",
      "CameraRotateLeft": "Q",
      "CameraRotateRight": "E",
      "ResetCameraRotation": "Home",
      "TimePause": "Space",
      "TimeNormal": "Alpha1",
      "TimeFast": "Alpha2",
      "TimeVeryFast": "Alpha3",
      "TimeSuperspeed": "Alpha4",
      "Screenshot": "F12",
      "ScreenshotMode": "F4",
      "ScreenshotModeCinematic": "C",
      "SetCinematicRotationTarget": "G",
      "ShowFPS": "F1",
      "ZoomIn": "PageDown",
      "ZoomOut": "PageUp",
      "FloorUp": "R",
      "FloorDown": "F",
      "ToggleGrid": "LeftControl",
      "FastCameraMovement": "LeftShift",
      "CityShortcutResearch": "R",
      "CityShortcutProduction": "P",
      "CityShortcutDistricts": "C",
      "CityShortcutVisualizations": "V",
      "CityShortcutTransportLines": "T",
      "Move": "M",
      "Delete": "Delete",
      "Pipette": "G",
      "Quicksave": "F5",
      "Quickload": "F9",
      "MouseLeftClick": "Mouse0",
      "MouseRightClick": "Mouse1",
      "Escape": "Escape"
    },
    "mods": []
  },
  "roadmap": {
    "$type": "RoadmapManager+Persistent, old",
    "givenVotes": [],
    "lastChecked": "0001-01-01T00:00:00"
  },
  "tutorial": {
    "$type": "TutorialManager+Persistent, old",
    "askedForTutorial": true,
    "knownTutorials": []
  }
}
